sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t aandreygch/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true aandreygch/react-test npm test

after_success:
  - docker build -t aandreygch/multi-client ./client
  - docker build -t aandreygch/multi-nginx ./nginx
  - docker build -t aandreygch/multi-server ./server
  - docker build -t aandreygch/multi-worker ./worker
  #Login into  the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push aandreygch/multi-client
  - docker push aandreygch/multi-nginx
  - docker push aandreygch/multi-server
  - docker push aandreygch/multi-worker  
  #test